service: sls-hello-world


provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    role:
      ${env:LAMBDA_ROLE_ARN}
    environment:
      STAGE: '${self:provider.stage}'
